name: "Copilot Runner"
description: "Generic GitHub Copilot CLI runner: installs CLI, executes a prompt with timeout, optionally publishes output."
inputs:
  copilot-token:
    description: "GitHub Copilot token (e.g. secrets.COPILOT_CLI)."
    required: true
  timeout:
    description: "Seconds before command is terminated."
    required: false
    default: "120"
  include-output:
    description: "Append output to job summary if true."
    required: false
    default: "true"
  prompt:
    description: "Prompt passed to Copilot CLI."
    required: false
    default: "Provide a concise analysis of the context supplied by previous steps."
  prompt-file:
    description: "Optional path to a file whose contents will be used as the prompt (overrides prompt)."
    required: false
    default: ""
  output-file:
    description: "Base filename for output (timestamp will always be appended before extension)."
    required: false
    default: "copilot_output.txt"
  model:
    description: "AI model to use (e.g. claude-sonnet-4.5, claude-sonnet-4, gpt-5)."
    required: false
    default: ""
  agent:
    description: "Custom agent to use (e.g. refactor-agent)."
    required: false
    default: ""
  extract-marker:
    description: "Optional text marker to extract content from (e.g. '## 🤖 AI Test Review'). If set, only content from this marker onwards is returned."
    required: false
    default: ""
outputs:
  raw:
    description: "Raw Copilot CLI output."
    value: ${{ steps.run-prompt.outputs.raw }}
  file:
    description: "Final output file name (if written)."
    value: ${{ steps.run-prompt.outputs.file }}
runs:
  using: "composite"
  steps:
    - name: Install GitHub Copilot CLI
      shell: bash
      run: sudo npm install -g @github/copilot@latest

    - name: Run Copilot prompt
      id: run-prompt
      shell: bash
      env:
        COPILOT_GITHUB_TOKEN: ${{ inputs.copilot-token }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_INCLUDE_OUTPUT: ${{ inputs.include-output }}
        INPUT_PROMPT: ${{ inputs.prompt }}
        INPUT_PROMPT_FILE: ${{ inputs.prompt-file }}
        INPUT_OUTPUT_FILE: ${{ inputs.output-file }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_AGENT: ${{ inputs.agent }}
        INPUT_EXTRACT_MARKER: ${{ inputs.extract-marker }}
      run: |
        echo "Authenticating with GitHub Copilot"
        copilot --version || echo "Copilot version check failed"

        # Determine final prompt source
        if [ -n "$INPUT_PROMPT_FILE" ]; then
          if [ -f "$INPUT_PROMPT_FILE" ]; then
            echo "Using prompt file: $INPUT_PROMPT_FILE"
            PROMPT_CONTENT="$(cat "$INPUT_PROMPT_FILE")"
          else
            echo "Prompt file not found: $INPUT_PROMPT_FILE" >&2
            exit 1
          fi
        else
            PROMPT_CONTENT="$INPUT_PROMPT"
        fi

        # Always append timestamp to output filename
        BASE_OUT="$INPUT_OUTPUT_FILE"
        TS=$(date +%Y%m%d%H%M%S)
        if [[ "$BASE_OUT" == *.* ]]; then
          NAME_NO_EXT="${BASE_OUT%.*}"
          EXT="${BASE_OUT##*.}"
          FINAL_OUT="${NAME_NO_EXT}-${TS}.${EXT}"
        else
          FINAL_OUT="${BASE_OUT}-${TS}"
        fi

        # Build copilot command arguments array
        COPILOT_ARGS=()
        if [ -n "$INPUT_MODEL" ]; then
          COPILOT_ARGS+=("--model" "$INPUT_MODEL")
          echo "Using model: $INPUT_MODEL"
        fi
        if [ -n "$INPUT_AGENT" ]; then
          COPILOT_ARGS+=("--agent=$INPUT_AGENT")
          echo "Using agent: $INPUT_AGENT"
        fi

        echo "Executing prompt (timeout=$INPUT_TIMEOUT) -> $FINAL_OUT"
        set +e
        timeout "$INPUT_TIMEOUT" copilot "${COPILOT_ARGS[@]}" -p "$PROMPT_CONTENT" > "${FINAL_OUT}.raw"
        exit_code=$?
        set -e
        if [ $exit_code -ne 0 ]; then
          echo "Copilot CLI exited with code $exit_code (timeout or error)."
        fi
        
        # Extract content from marker if specified
        if [ -n "$INPUT_EXTRACT_MARKER" ]; then
          if grep -q "$INPUT_EXTRACT_MARKER" "${FINAL_OUT}.raw"; then
            sed -n "/$INPUT_EXTRACT_MARKER/,\$p" "${FINAL_OUT}.raw" > "$FINAL_OUT"
            echo "Extracted content from marker: $INPUT_EXTRACT_MARKER"
          else
            # Fallback: use full output if marker not found
            cp "${FINAL_OUT}.raw" "$FINAL_OUT"
            echo "Warning: Could not find marker '$INPUT_EXTRACT_MARKER', using full output"
          fi
        else
          # No marker specified, use full output
          mv "${FINAL_OUT}.raw" "$FINAL_OUT"
        fi
        
        UNIQUE_DELIM="__COPILOT_RAW_$(date +%s%N)__"
        echo "Using unique delimiter $UNIQUE_DELIM for multi-line output"
        {
          printf 'raw<<%s\n' "$UNIQUE_DELIM"
          cat "$FINAL_OUT"
          printf '\n%s\n' "$UNIQUE_DELIM"
        } >> "$GITHUB_OUTPUT"

        echo "file=$FINAL_OUT" >> "$GITHUB_OUTPUT"

        if [ "$INPUT_INCLUDE_OUTPUT" = "true" ]; then
          echo "### Copilot CLI Output ($FINAL_OUT)" >> "$GITHUB_STEP_SUMMARY"
          cat "$FINAL_OUT" >> "$GITHUB_STEP_SUMMARY"
        fi

        cat "$FINAL_OUT" || true